# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Workflow

on:
  push:
    branches: [ "ci-workflow" ]
  pull_request:
    branches: [ "ci-workflow" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Install Docker Compose v2
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and run containers using Docker Compose
      run: docker compose up -d --build
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        JWT_KEY: ${{ secrets.JWT_KEY }}

    - name: Wait for containers to be ready
      run: sleep 30

    - name: Check Docker Compose status
      run: docker compose ps

    - name: Check logs for citygems_api
      run: docker compose logs citygems_api

    - name: Install dependencies in citygems_api container
      run: docker compose exec -T citygems_api yarn install
      env:
        JWT_KEY: ${{ secrets.JWT_KEY }}

